### ISSUE TITLE
[FEAT] 상품조회 뷰

### ISSUE THREAD

**Issue by wkdyujin** [UMC-GetIT/GetIT-android#34]
## ☝️  Issue
상품조회 뷰 생성

## 📃 To-do
- [x] 제품 카테고리(노트북, 휴대폰 등)
- [x] 제품 세부 카테고리(화면크기, 가격 등)
- [x] 전체 상품 리스트
