### ISSUE TITLE
[FEAT] 카테고리 조회 기능

### ISSUE THREAD

**Issue by wkdyujin** [UMC-GetIT/GetIT-android#48]
## ☝️  Issue
카테고리 조회 뷰 기능

## 📃 To-do
- [x] 제품 카테고리 선택 버튼 이벤트
- [x] 제품 상세 카테고리 선택 버튼 이벤트
- [x] 카테고리로 서버 연결
- [x] 제품 상세 뷰 전환
